{
    "version": "12.0.1.0.1",
    "name": "procurement_purchase_no_merge",
    "summary": "Prevent POs merging, create 1:1 relationship for SO:PO",
    "category": "Purchases",
    # 'live_test_url': "",
    "images": [],
    "application": False,
    "author": "Glodo",
    "website": "https://www.glodo.uk",
    "license": "Other proprietary",
    # 'price: 250.00,
    # 'currency: "EUR",
    "depends": ["sale_purchase", "sale_stock"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [
        "views/views.xml",
    ],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
